agregar pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,15 +20,6 @@ on:
           - myproyecto1
           - myproyecto2
           - myproyecto3
-      deploy_proyectos:
-        description: 'Selecciona el proyecto a desplegar (Deploy)'
-        required: true
-        default: 'myproyecto1'
-        type: choice
-        options:
-          - myproyecto1
-          - myproyecto2
-          - myproyecto3
 
 env:
     TAGS: 1.0.${{ github.run_number }}
@@ -89,45 +80,45 @@ jobs:
             echo "docker push $ecr_uri"
             echo "docker push $ecr_uri"
           done
-  Deploy:
-    name: Deploy DEV
-    runs-on: ubuntu-latest
-    needs: build
-    permissions:
-      contents: read
-      id-token: write  # Required for OIDC authentication
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # Deploy:
+  #   name: Deploy DEV
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   permissions:
+  #     contents: read
+  #     id-token: write  # Required for OIDC authentication
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Deploy to Lambda DEV
-        run: |  
-          echo "Desplegando a Lambda DEV"
-          PROYECTO="${{ inputs.deploy_proyectos || 'myproyecto1' }}"
+  #     - name: Deploy to Lambda DEV
+  #       run: |  
+  #         echo "Desplegando a Lambda DEV"
+  #         PROYECTO="${{ inputs.proyectos || 'myproyecto1' }}"
 
-          # Buscar el proyecto en config.yml por proyectoid
-          count=$(yq e '.proyectos | length' ./config.yml)
-          encontrado=false
-          for i in $(seq 0 $(($count - 1))); do
-            pid=$(yq e ".proyectos[$i].proyectoid" ./config.yml)
-            if [ "$pid" == "$PROYECTO" ]; then
-              encontrado=true
-              proyectoid=$pid
-              ecrRepositoryDEV=$(yq e ".proyectos[$i].ecrRepositoryDEV" ./config.yml)
-              LambdaDEV=$(yq e ".proyectos[$i].LambdaDEV" ./config.yml)
-              break
-            fi
-          done
+  #         # Buscar el proyecto en config.yml por proyectoid
+  #         count=$(yq e '.proyectos | length' ./config.yml)
+  #         encontrado=false
+  #         for i in $(seq 0 $(($count - 1))); do
+  #           pid=$(yq e ".proyectos[$i].proyectoid" ./config.yml)
+  #           if [ "$pid" == "$PROYECTO" ]; then
+  #             encontrado=true
+  #             proyectoid=$pid
+  #             ecrRepositoryDEV=$(yq e ".proyectos[$i].ecrRepositoryDEV" ./config.yml)
+  #             LambdaDEV=$(yq e ".proyectos[$i].LambdaDEV" ./config.yml)
+  #             break
+  #           fi
+  #         done
 
-          if [ "$encontrado" == "false" ]; then
-            echo "ERROR: Proyecto '$PROYECTO' no encontrado en config.yml"
-            exit 1
-          fi
+  #         if [ "$encontrado" == "false" ]; then
+  #           echo "ERROR: Proyecto '$PROYECTO' no encontrado en config.yml"
+  #           exit 1
+  #         fi
 
-          echo "---- Variables cargadas ----"
-          echo "proyectoid:       $proyectoid"
-          echo "ecrRepositoryDEV: $ecrRepositoryDEV"
-          echo "LambdaDEV:        $LambdaDEV"
-          echo "----------------------------"
+  #         echo "---- Variables cargadas ----"
+  #         echo "proyectoid:       $proyectoid"
+  #         echo "ecrRepositoryDEV: $ecrRepositoryDEV"
+  #         echo "LambdaDEV:        $LambdaDEV"
+  #         echo "----------------------------"
 
-          echo "aws lambda update-function-code --function-name $LambdaDEV --image-uri ${{ env.AWS_USER }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ecrRepositoryDEV:${{ env.TAGS }}"
+  #         echo "aws lambda update-function-code --function-name $LambdaDEV --image-uri ${{ env.AWS_USER }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ecrRepositoryDEV:${{ env.TAGS }}"
